apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
  labels:
    app: second-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: second-app
        image: hoangit3/second-app
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service

metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: second-app
  ports:
    - port: 8085
      targetPort: 8085
